### ISSUE TITLE
SIGCHLD side effects

### ISSUE THREAD

**Issue by jeroen** [jeroen/sys#10]
Our `SIGCHLD`handler cleans child processes before the parent can get to the exit code. This affects all subprocesses:

```r
res <- system("ping sdffsdsfsdfasdf.xyz", T)
attr(res, "status")
# [1] 68
```

However after sys is loaded the exit code is always 0:

```r
library(sys)
res <- system("ping sdffsdsfsdfasdf.xyz", T)
attr(res, "status")
# NULL
```

This is bad. We should find a way to mark a child spawned by `sys` and only clean up these processes in our SIGCHLD handler.

**Comment by jeroen** [comment]
Alternatively we should abandon `SIGCHLD` and make the user manually clean children, or do it in some handle finalizer.

**Comment by gaborcsardi** [comment]
Yeah, that's bad.

> Alternatively we should abandon SIGCHLD and make the user manually clean children, or do it in some handle finalizer.

That's fine with me, I can write a wrapper.

**Comment by jeroen** [comment]
Actuall are you sure zombies are a problem in the first place? At least on OSX:

```r
for(i in 1:100) print(exec_background('whoami'))
```

I am not seeing zombies in `top`, even when disabling the signal handler.

**Comment by jeroen** [comment]
How does the parallel SIGCHLD handler avoid this problem?

**Comment by jeroen** [comment]
Ah I see it now. mcparallel keep track of a list of children that were spawned and only cleans up those.

**Comment by jeroen** [comment]
I have added a `exec_status` function to check the exit status of a `pid`, and optionally wait for it. The `SIGCHLD` handler is now commented-out in master until we find a solution without side effects. 

@gaborcsardi can you check if `exec_background()` + `exec_status()` suffices for your use cases?

I still need to implement this for windows btw.
