### ISSUE TITLE
Support `env` argument to exec_wait?

### ISSUE THREAD

**Issue by fritzo** [jeroen/sys#15]
`exec_wait()` looks like a great alternative to `system2()`, but for some use cases, I need to specify an environment via the `env` argument. Is there a work-around, or is this possible easy to add to `exec_wait`?

**Comment by fritzo** [comment]
It looks like `Sys.setenv()` is a viable workaround.

**Comment by jeroen** [comment]
Environment variables get inherited by the child process so there is usually no need to pass them manually. Indeed a typical pattern is to use:

```r
myprog <- function(args){
  Sys.setenv(FOO="BAR")
  on.exit(Sys.unsetenv("FOO")
  sys::exec_wait("myprog", args)
}
