### ISSUE TITLE
Long total args length causes session crash on Windows

### ISSUE THREAD

**Issue by raymondben** [jeroen/sys#17]
I've run across odd behaviour where a command will work fine on Linux but cause a session crash on Windows. I think it is caused by long argument lists. e.g., this runs without crashing on Linux but crashes on Windows:

`
blah <- sys::exec_internal("curl",args=c("--ssl-no-revoke","--verbose","--retry","11","--connect-timeout",999,"--cookie-jar","/this/is/a/very/long/path/just/to/make/the/total/argument/length/long","--max-filesize",99999999,"--max-redirs",11111,"--max-time",111111,"--user-agent","jdfhdskhfkldahfildiufndskjflkashflasshflkadjlfiadjflkajdshflisdhlfasdfkjdshlofhlkfhdliuafsshlfdifhdalhudf","--url","https://www.google.com/"))
`

Making it shorter by dropping e.g. the `"--user-agent"` parm (and the long parm value string that follows it) and all is well. This happens for me using other long commands (not just `curl`) and it only seems to be the total argument length that matters.

UPDATE: forgot to mention that `system2` does not crash with the long version.

Linux `sessionInfo()`:

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.1 sys_1.4
```

And Windows:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1    sys_1.4       
```

**Comment by raymondben** [comment]
@jeroen any thoughts on this? This is the relevant code in win32/exec.c:
```
const char * cmd = CHAR(STRING_ELT(command, 0));
  char argv[MAX_PATH] = "";
  for(int i = 0; i < Rf_length(args); i++){
    strcat(argv, CHAR(STRING_ELT(args, i)));
    strcat(argv, " ");
  }
```
`MAX_PATH` is the maximum allowed path length, which is 260 characters on Windows. As I understand things (but I could be totally wrong here!) this applies to the command itself, not to the total argv string length (which has max length 32768). From https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx:
 
> The command line to be executed. The maximum length of this string is 32,768 characters, including the Unicode terminating null character. If lpApplicationName is NULL, the module name portion of lpCommandLine is limited to MAX_PATH characters.

So `MAX_PATH` applies to the command, which has already been prepended to `args` here (in `exec.R::execute`) but the total argv length should be 32768 max?? But, like I said, I could be totally wrong ...

**Comment by jeroen** [comment]
Thanks for catching this! Fixed in https://github.com/jeroen/sys/commit/89ce49329ac6589d9d9bb490339f5d69381c526d. Need to test more.
