### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by CameronHosking** [jeroen/sys#20]
I may not be understanding how the callback function works. But I thought that it was a function that would be called with a raw vector representing the text that the executed program printed to stdout. 
In this case the following code shout print "foo bar". It does not.

```
library(sys)

call_back_function = function(output)
{
  print(rawToChar(output))
}

if(.Platform$OS.type == 'windows'){
  exec_wait("cmd",args = c('/C', 'echo', 'foo bar'),std_out = call_back_function)
} else {
  exec_wait("echo",args = c('foo bar'),std_out = call_back_function)
}
```
Instead on both windows and unix, stdout is discarded.

**Comment by jeroen** [comment]
Sorry about this, I seem to have overlooked this case when refactoring a while back. It's actually working internally but I wasn't passing down the argument. Anyway should be fixed now:

```r
remotes::install_github("jeroen/sys")
```

**Comment by CameronHosking** [comment]
Yep fixed now, 
Cheers for that
