### ISSUE TITLE
Failed to execute 'C:\...\Rterm.exe' (The handle is invalid)

### ISSUE THREAD

**Issue by kylebaron** [jeroen/sys#21]
Thanks for sys ... it's a breath of fresh air compared to using `system()`. 

Wondering if you've seen this before?  I can't reproduce it on my Windows box or on winbuilder, but for some reason seeing it with `rhub::check_on_windows()`.   I can bring the issue over there, but wondered if there was interest here in case there isn't a _problem_ per se with the rhub setup.

From checking this package:

https://github.com/mrgsolve/systest/blob/master/R/test.R#L11-L16

There is another equivalent call using `system2()` that I don't think generates this error.

```r
* checking examples ... ERROR
The error most likely occurred in:
> ### Name: sys_test_internal
> ### Title: Test exec_internal
> ### Aliases: sys_test_internal
> 
> ### ** Examples
> 
> 
> 
> sys_test_internal()
Error: Failed to execute 'C:\PROGRA~1\R\R-35~1.2\bin\x64\Rterm.exe' (The handle is invalid)
Execution halted
```

**Comment by jeroen** [comment]
I think that error happens on Windows when you try to run a command that does not exist...

**Comment by jeroen** [comment]
OK that was a bug, you should now get the proper error message. Still now sure why it errors though...

**Comment by jeroen** [comment]
Your example seems to work on my Windows vm. What does your machine rerturn for this:

```r
Sys.which(sys:::rbin())
```

**Comment by kylebaron** [comment]
It works on my Windows machine too and on winbuilder.  Only happens for me on rhub.  So definitely might be some quirky setting there.  But so far, the equivalent calls seem to work ok with `system2`.

```r
> Sys.which(sys:::rbin())
C:\PROGRA~1\R\R-35~1.2\bin\x64\Rterm.exe
```

If I test with `exec_internal("date")`
https://github.com/mrgsolve/systest/blob/master/R/test.R#L12

```r
E  checking examples
   Running examples in 'systest-Ex.R' failed
   The error most likely occurred in:
   
   > ### Name: sys_test_internal
   > ### Title: Test exec_internal
   > ### Aliases: sys_test_internal
   > 
   > 
   > 
   > ### ** Examples
   > 
   > sys_test_internal()
   Error: Failed to execute 'C:\Rtools34\bin\date.exe' (The handle is invalid)
   Execution halted
```

**Comment by jeroen** [comment]
Hmm that's interesting. I'll try to figure out what is going wrong on r-hub. At least if you install the dev version of sys, you should get a proper error message now:

```r
remotes::install_github("jeroen/sys")
```

**Comment by kylebaron** [comment]
Thanks.

**Comment by jeroen** [comment]
I think there are some security restrictions in r-hub that limit the spawning of certain processes. When checking the sys package we get a lot of `Access is Denied` errors: https://artifacts.r-hub.io/sys_2.1.9000.tar.gz-fa81c1764bab4aae8949296ad8cb89c4/sys.Rcheck/tests_x64/testthat.Rout.fail
