### ISSUE TITLE
Fails to compile in with -std=c99

### ISSUE THREAD

**Issue by dth2** [jeroen/sys#23]
I am trying tin install several packages that rely on sys but sys fails to compile.  I am running r_3.5.1 and I get the following on install. 

 install.packages("sys")
Installing package into ‘/gscratch/home/dth2/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.cnr.berkeley.edu/src/contrib/sys_2.1.tar.gz'
Content type 'application/x-gzip' length 25636 bytes (25 KB)
==================================================
downloaded 25 KB

* installing *source* package ‘sys’ ...
** package ‘sys’ successfully unpacked and MD5 sums checked
Building without AppArmor (Linux)
** libs
rm -f sys.so exec.o fork.o init.o util.o
icc -std=gnu99 -I"/sw/R-3.5.1/lib64/R/include" -DNDEBUG -DSYS_BUILD_SAFE  -I/usr/local/include   -fpic  -g -O2 -std=c99  -c exec.c -o exec.o
exec.c(24): warning #266: function "kill" declared implicitly
    kill(0, SIGKILL); // kills process group
    ^

exec.c(31): warning #266: function "sigemptyset" declared implicitly
    sigemptyset(&block_sigchld);
    ^

exec.c(32): warning #266: function "sigaddset" declared implicitly
    sigaddset(&block_sigchld, SIGCHLD);
    ^

exec.c(33): warning #266: function "sigprocmask" declared implicitly
    sigprocmask(SIG_BLOCK, &block_sigchld, NULL);
    ^

exec.c(33): error: identifier "SIG_BLOCK" is undefined
    sigprocmask(SIG_BLOCK, &block_sigchld, NULL);
                ^

exec.c(38): warning #266: function "sigemptyset" declared implicitly
    sigemptyset(&block_sigchld);
    ^

exec.c(39): warning #266: function "sigaddset" declared implicitly
    sigaddset(&block_sigchld, SIGCHLD);
    ^

exec.c(40): warning #266: function "sigprocmask" declared implicitly
    sigprocmask(SIG_UNBLOCK, &block_sigchld, NULL);
    ^

exec.c(40): error: identifier "SIG_UNBLOCK" is undefined
    sigprocmask(SIG_UNBLOCK, &block_sigchld, NULL);
                ^

exec.c(52): warning #266: function "fdopen" declared implicitly
      FILE *stream = fdopen(STDERR_FILENO, "w");
                     ^

exec.c(211): warning #266: function "strdup" declared implicitly
        argv[i] = strdup(CHAR(STRING_ELT(args, i)));
                  ^

exec.c(252): warning #266: function "kill" declared implicitly
          warn_if(kill(pid, SIGINT), "interrupt child");
                  ^

exec.c(255): warning #266: function "kill" declared implicitly
          warn_if(kill(pid, SIGKILL), "force kill child");
                  ^

exec.c(263): warning #266: function "kill" declared implicitly
        warn_if(kill(pid, killcount ? SIGKILL : SIGINT), "kill child");
                ^

exec.c(290): warning #266: function "strsignal" declared implicitly
                       CHAR(STRING_ELT(command, 0)), strsignal(signal));
                                                     ^

exec.c(305): warning #266: function "usleep" declared implicitly
      usleep(100*1000);
      ^

compilation aborted for exec.c (code 2)
make: *** [exec.o] Error 2
ERROR: compilation failed for package ‘sys’
* removing ‘/gscratch/home/dth2/R/x86_64-pc-linux-gnu-library/3.5/sys’

The downloaded source packages are in
        ‘/tmp/RtmpOYo662/downloaded_packages’
Warning message:
In install.packages("sys") :
  installation of package ‘sys’ had non-zero exit status
>

**Comment by jeroen** [comment]
Which operating system is this? You are compiling with `icc` instead of `gcc`?

**Comment by dth2** [comment]
We are running CentOS 7 Linux

**Comment by jeroen** [comment]
It works on my CentOS 7 with gcc. Why are compiling with `icc` instead of `gcc`?

**Comment by dth2** [comment]
I will try with gcc.  For now I have found that reverting devtools, httr and openssl avoids the dependency all together.

**Comment by jeroen** [comment]
Sure but you should probably figure out why your compiler is misconfigured.

**Comment by tpilz** [comment]
I have exactly the same problem as described in the first post (`error: identifier "SIG_UNBLOCK" is undefined`) with icc (by default). When just switching to gcc the error persists.

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 12 SP3
```
This occurred on the HPC I am working on (using a system wide installation of R), so my possibilities are limited. Any ideas where this could come from? Missing includes?

**Comment by jeroen** [comment]
What C standard are you compiling with? You need `-std=gnu99`. Can you show me the output of your:

```
R CMD config CC
R CMD config CFLAGS
```

**Comment by jeroen** [comment]
Alternatively we could enforce this by defining [`_GNU_SOURCE`](https://github.com/jeroen/sys/commit/785276a8e2912b104ce6736aa614a2a7cccac095) in the package, can you try to installing form the [gnu branch](https://github.com/jeroen/sys/tree/gnu):

```r
remotes::install_github("jeroen/sys@gnu")
```

**Comment by tpilz** [comment]
`-std=gnu99` did the trick. I was using C99 standard both with icc and gcc, which did not work.
