### ISSUE TITLE
Missing call to setgroups before setuid

### ISSUE THREAD

**Issue by QuLogic** [jeroen/sys#24]
Fedora builds are currently outputting this error:
```
missing-call-to-setgroups-before-setuid:
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```
Since this package seems to only be a wrapper, that's probably a false positive. However, it doesn't appear that `setgroups` or `initgroups` is exposed for the higher-level code to use.

**Comment by jeroen** [comment]
I plan to remove this part of the code anyway for the next release, so the problem should solve itself.

**Comment by jeroen** [comment]
This code has been removed in sys 3.0 (on cran now).
