### ISSUE TITLE
OpenBSD unit tests

### ISSUE THREAD

**Issue by jeroen** [jeroen/sys#3]
Run unit tests on OpenBSD:

```r
devtools::install_github("jeroenooms/sys")
testthat::test_package("sys")
```

**Comment by dhwolfskill** [comment]
Following advice from elsewhere, I used the "_canonical_ and _documented_ way" to test (successfully) -- though this is under FreeBSD, not OpenBSD -- thus:

g1-252(11.0-S)[7] unzip sys-master.zip 
Archive:  sys-master.zip
ff1eb6c18185954cab4d986579c7bf68d8e66d2c
...
  inflating: sys-master/tests/testthat/test-stdout.R  

g1-252(11.0-S)[11] R CMD build sys-master/
\* checking for file ‘sys-master/DESCRIPTION’ ... OK
\* preparing ‘sys’:
\* checking DESCRIPTION meta-information ... OK
\* cleaning src
\* checking for LF line-endings in source and make files
\* checking for empty or unneeded directories
\* building ‘sys_1.1.tar.gz’

g1-252(11.0-S)[12] echo $?
0
g1-252(11.0-S)[13] R CMD check sys_1.1.tar.gz 
\* using log directory ‘/tmp/sys.Rcheck’
...
\* checking package dependencies ... ERROR
Package suggested but not available: ‘testthat’
....

[Installed "testthat"....]

g1-252(11.0-S)[14] R CMD check sys_1.1.tar.gz
\* using log directory ‘/tmp/sys.Rcheck’
\* using R version 3.3.2 (2016-10-31)
\* using platform: amd64-portbld-freebsd11.0 (64-bit)
\* using session charset: UTF-8
\* checking for file ‘sys/DESCRIPTION’ ... OK
\* checking extension type ... Package
\* this is package ‘sys’ version ‘1.1’
\* package encoding: UTF-8
\* checking package namespace information ... OK
\* checking package dependencies ... OK
\* checking if this is a source package ... OK
\* checking if there is a namespace ... OK
\* checking for executable files ... OK
\* checking for hidden files and directories ... OK
\* checking for portable file names ... OK
\* checking for sufficient/correct file permissions ... OK
\* checking whether package ‘sys’ can be installed ... OK
\* checking installed package size ... OK
\* checking package directory ... OK
\* checking DESCRIPTION meta-information ... OK
\* checking top-level files ... OK
\* checking for left-over files ... OK
\* checking index information ... OK
\* checking package subdirectories ... OK
\* checking R files for non-ASCII characters ... OK
\* checking R files for syntax errors ... OK
\* checking whether the package can be loaded ... OK
\* checking whether the package can be loaded with stated dependencies ... OK
\* checking whether the package can be unloaded cleanly ... OK
\* checking whether the namespace can be loaded with stated dependencies ... OK
\* checking whether the namespace can be unloaded cleanly ... OK
\* checking loading without being on the library search path ... OK
\* checking dependencies in R code ... OK
\* checking S3 generic/method consistency ... OK
\* checking replacement functions ... OK
\* checking foreign function calls ... OK
\* checking R code for possible problems ... OK
\* checking Rd files ... OK
\* checking Rd metadata ... OK
\* checking Rd cross-references ... OK
\* checking for missing documentation entries ... OK
\* checking for code/documentation mismatches ... OK
\* checking Rd \usage sections ... OK
\* checking Rd contents ... OK
\* checking for unstated dependencies in examples ... OK
\* checking line endings in C/C++/Fortran sources/headers ... OK
\* checking compiled code ... OK
\* checking examples ... NONE
\* checking for unstated dependencies in ‘tests’ ... OK
\* checking tests ...
  Running ‘testthat.R’
 OK
\* checking PDF version of manual ... OK
\* DONE

Status: OK

g1-252(11.0-S)[15] echo $?
0
g1-252(11.0-S)[16] 

Looks good to me!

**Comment by jeroen** [comment]
OK perfect, thanks!
