### ISSUE TITLE
Complitation error on cluster

### ISSUE THREAD

**Issue by aleighbrown** [jeroen/sys#30]
hello, 
Trying to install into my local folder on a cluster, error as follow:
"* installing *source* package ‘sys’ ...
** package ‘sys’ successfully unpacked and MD5 sums checked
** libs
gcc -I"/share/apps/R-3.5.2/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -I/share/apps/zlib-1.2.8/include -I/share/apps/bzip2-1.0.6/include -I/share/apps/xz-5.2.1/include/ -I/share/apps/pcre-8.39/include -I/share/apps/curl-7.48/include  -c exec.c -o exec.o
exec.c: In function ‘C_execute’:
exec.c:206:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 3; i < sysconf(_SC_OPEN_MAX); i++) {
     ^
exec.c:206:5: note: use option -std=c99 or -std=gnu99 to compile your code
exec.c:215:13: error: redefinition of ‘i’
     for(int i = 0; i < len; i++){
             ^
exec.c:206:14: note: previous definition of ‘i’ was here
     for (int i = 3; i < sysconf(_SC_OPEN_MAX); i++) {
              ^
exec.c:215:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 0; i < len; i++){
     ^
make: *** [/share/apps/R-3.5.2/lib64/R/etc/Makeconf:162: exec.o] Error 1
ERROR: compilation failed for package ‘sys’"

**Comment by aleighbrown** [comment]
R CMD config CC = gcc
R CMD config CFLAGS = -I/share/apps/zlib-1.2.8/include -I/share/apps/bzip2-1.0.6/include -I/share/apps/xz-5.2.1/include/ -I/share/apps/pcre-8.39/include -I/share/apps/curl-7.48/include

**Comment by aleighbrown** [comment]
Description:	CentOS release 6.5 (Final)
Release:	6.5
Codename:	Final

**Comment by jeroen** [comment]
R widely assumes C99 and it seems like your compiler defaults to C89. I'm not sure where you got this version of R, but it needs to be built with `CC = gcc -std=gnu99`. If you download the official [R-devel](https://apps.fedoraproject.org/packages/R-devel) from EPEL I think this should be the case.

The best way to solve your situation is set `CC = gcc -std=gnu99` variable in this file:

```
vi $(R RHOME)/etc/Makeconf
```
