### ISSUE TITLE
Interacting with other systems interfaces who run on interactive mode

### ISSUE THREAD

**Issue by carlosparadis** [jeroen/sys#33]
Hi, 

I currently have to interact with a system which the cli interface requires an interactive shell environment. Trying to invoke it throws an error via system2 or any exec_. Is there any way to work this around from an R console? 

The tool would work if I launch R via the terminal, and then execute system2() or exec_*, just not from the R console we typically see in R Studio (and is much needed for managing and creating packages).

**Comment by jeroen** [comment]
I don't thinks so, `system2` is made to run a command and wait for the output. You might try the `ps` package which allows you to spawn a process and then send/pull data to it.

**Comment by carlosparadis** [comment]
@jeroen Thank you so much for the quick follow-up, I will try to follow the suggested route and close the issue :)
