### ISSUE TITLE
sys to run ubuntu in WSL

### ISSUE THREAD

**Issue by dikiprawisuda** [jeroen/sys#35]
Hi, I am sorry if this is irrelevant. I found your github in the google search and saying that this is like an upgraded version of system2() caught me.
I have been struggling with my ideal of streamlining the computing process using R. I am quite new in the informatics (biology background) so again, sorry if this is out of context. 
I have a windows desktop with windows subsystem linux, miniconda, and windows terminal installed. I have played with some linux's app (QIIME2) within the windows terminal. But now, I want to run a function (cutadapt()) within R using system2(). It was unsuccessful. 

Was it unsuccessful because system2() is essentially running command prompt and deliver the args etc to it? So, as long as I am unable to run cutadapt() within command prompt (Windows), I will not be able to run system2(cutadapt, ...) ?
If this is correct, is it possible to change the target, for example from cmd.exe to ubuntu.exe?

Thank you for your attention.

**Comment by jeroen** [comment]
Sorry I don't understand your question. Can you try to include example code illustrating what was unsuccessful?

**Comment by dikiprawisuda** [comment]
I am sorry I think it is not suitable to ask about my problem here. 
I am terribly sorry for this.
