### ISSUE TITLE
Do not wait for background processes

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/sys#6]
Use the `SIGCHLD` handler and `wait()` to get their error status, see #5.

**Comment by gaborcsardi** [comment]
I mean, when you start them, do not wait for 1/2 second.

**Comment by jeroen** [comment]
The 1/2 waiting is to see if `execv()` was successful. How would `SIGCHLD` would help here? We would still have to wait for a potential `SIGCHILD` to check if the process launched successfully?

**Comment by jeroen** [comment]
I really want to avoid the types of race conditions from `mcparallel`

**Comment by gaborcsardi** [comment]
I think you will get a SIGCHLD if the `execvp` fails. This allows checking the exit status of the process later, if desired. So if the `execvp` fails, just exit with 255 or whatever you like.

If the user really want to check the process 1/2 sec later, then they can.

**Comment by gaborcsardi** [comment]
But if you really want to catch if the `execvp` failed, you can do this:
http://stackoverflow.com/a/13710144/604364

> This is a classic problem with a very elegant solution. Before forking, create a pipe in the parent. After fork, the parent should close the writing end of the pipe, and block attempting to read from the reading end. The child should close the reading end and set the close-on-exec flag, using fcntl, for the writing end.

> Now, if the child calls execvp successfully, the writing end of the pipe will be closed with no data, and read in the parent will return 0. If execvp fails in the child, write the error code to the pipe, and read in the parent will return nonzero, having read the error code for the parent to handle.

**Comment by gaborcsardi** [comment]
So if you do the pipe trick, then this is independent of the `SIGCHLD` handler. (Which is also **really** needed to get rid of zombies.)

**Comment by jeroen** [comment]
I do want to catch `exec` failures immediately, even for background executions. I really don't like pushing this sort of complexity to the user. 

The problem in our scenario is that we do not control the program that is being executed, so I am not sure we can use the above solution? In particular this part:

> Now, if the child calls execvp successfully, the writing end of the pipe will be closed

Who is closing if we do not control the executed program? Anyway if you know how to implement this without breaking everything else, that would be great.

**Comment by jeroen** [comment]
Yes the SIGCHLD would be nice too. This is only needed for background executions, right? I think the final call to `waitpid()` cleans up the child in case of the blocking version.

**Comment by gaborcsardi** [comment]
> Who is closing that if we do not control the executed program?

The `execvp` call closes that automatically.

**Comment by gaborcsardi** [comment]
> Yes the SIGCHLD would be nice too. This is only needed for background executions, right? I think the final call to waitpid() cleans up the child in case of the blocking version.

Right.

**Comment by jeroen** [comment]
Ah right I get it now, the kernel will close it if you have marked it as close-on-exec. OK that makes sense I guess.

**Comment by gaborcsardi** [comment]
So what is this `failure` pipe in the code? That looks exactly what I was talking about....

**Comment by jeroen** [comment]
Yes it's very similar. It sends the `errno` to the parent in case the `execv` failed. However I was unaware of the `close-on-exec` trick. I think I can just repurpose that to use close-on-exec instead of waiting for the child...
